authorize_headers: &authorize_headers
  headers:
    Authorization: "Bearer {access_token}"

name: Test login
variables:
  a: 1
  b: 2
  c: 3
stages:
  - name: Authenticate user
    request:
      url: "https://login.company.com/auth/token"
      method: POST
      data:
        username: fred
        password: 123secret
        grant_type: password
      headers:
        Authorization: Basic c2VjcmV0IHNlY3JldCBzZWNyZXQgc2VjcmV0IHNlY3JldCBzZWNyZXQgc2VjcmV0=
    assert:
      - response.status_code == 200

    register:
      access_token: response.json()['access_token']

  - name: List opportunities
    request:
      url: "https://api.company.com/opportunities"
      <<: *authorize_headers
    assert:
      - response.status_code == 200

  - name: List users
    request:
      url: "https://api.company.com/user/profile"
      <<: *authorize_headers
    assert:
      - "response.status_code == 200"
      - "'results' in response.json()"
      - "'count' in response.json()"
      - "'next' in response.json()"
      - "'previous' in response.json()"
